### ISSUE TITLE
Server Lag and Repative Crashing

### ISSUE THREAD

**Issue by kentros38** [LunaPixelStudios/Better-Minecraft#35]
I have been running the Better Minecraft 1.18 on Forge in a hosted environment for a few friends on a server. 

In short, the lag is ridiculous and the server crashes constantly even when one person is on the server. It's on a dedicated 6 GB server so there shouldn't be an issue. If you stay within a 10 block radius of your normal area. i.e house and such, there isn't an issue. If someone uses a waystone then everyone needs to be aware and stop moving before we lag backward and die somehow. It's infuriating and I am trying to resolve it but I am unable to find a proper resolution. My last couple crash logs were very similar so I attached the most recent for you to take a look at. I have tried using chunky pre-world generator but that ends up crashing the server too. Any configuration update or advice would be greatly appreciated because I can't keep getting text to restart the server whenever I leave for anything.

Not trying to be rude, just need help and don't want to have to make my friends restart their stuff because there isn't a resolution

[crash-2022-01-16_22.57.48-server.txt](https://github.com/LunaPixelStudios/Better-Minecraft/files/7879291/crash-2022-01-16_22.57.48-server.txt)

**Comment by GlitchDoctor01** [comment]
I have exactly that problem for fabric version, also tried pregenerate chunks, but it doesn't help. Here some crash logs:

[crash-2022-01-17_09.19.54-server.txt](https://github.com/LunaPixelStudios/Better-Minecraft/files/7879493/crash-2022-01-17_09.19.54-server.txt)
[crash-2022-01-17_08.47.14-server.txt](https://github.com/LunaPixelStudios/Better-Minecraft/files/7879494/crash-2022-01-17_08.47.14-server.txt)
[crash-2022-01-17_08.25.18-server.txt](https://github.com/LunaPixelStudios/Better-Minecraft/files/7879496/crash-2022-01-17_08.25.18-server.txt)
[crash-2022-01-16_21.17.24-server.txt](https://github.com/LunaPixelStudios/Better-Minecraft/files/7879499/crash-2022-01-16_21.17.24-server.txt)
[crash-2022-01-17_08.09.16-server.txt](https://github.com/LunaPixelStudios/Better-Minecraft/files/7879497/crash-2022-01-17_08.09.16-server.txt)
[crash-2022-01-17_00.05.26-server.txt](https://github.com/LunaPixelStudios/Better-Minecraft/files/7879498/crash-2022-01-17_00.05.26-server.txt)

**Comment by SharkieTV** [comment]
@kentros38 @GlitchDoctor01 Who's your server host?
@kentros38 @GlitchDoctor01 On what version of the modpack did you start your world?
@kentros38 Are you pregenerating the chunks while playing on the server?

**Comment by GlitchDoctor01** [comment]
@SharkieTV 
For host i use my own dedicated server with next characteristics:

Intel Core i5-3550 4x3.3 GHz 
8GB DDR3
2x2TB SATA HDD in LVM+RAID1 Mode 
OS is Ubuntu 20.04 LTS

Minecraft version is 1.18.1 and modpack version is Better Minecraft [FABRIC] v11
also i pregenerate chunks only when nobody playing on the server

**Comment by SharkieTV** [comment]
@GlitchDoctor01 Ill place a v12 out tomorrow to see if that fixes it.

**Comment by kentros38** [comment]
@SharkieTV 

Server Host: https://ggservers.com/minecrafthosting I have a 6GB standard
Modpack is: https://imgur.com/a/BTWY1JY
And for generating chunks, I initially was trying with others on but realized that's a bad idea, started doing it with no one on and it would still crash while I was gone or something and then no one could get on.

Some more crash logs if you wanted to take a look:
[crash-2022-01-14_11.03.40-server.txt](https://github.com/LunaPixelStudios/Better-Minecraft/files/7884812/crash-2022-01-14_11.03.40-server.txt)
[crash-2022-01-14_13.23.26-server.txt](https://github.com/LunaPixelStudios/Better-Minecraft/files/7884813/crash-2022-01-14_13.23.26-server.txt)
[crash-2022-01-14_19.03.40-server.txt](https://github.com/LunaPixelStudios/Better-Minecraft/files/7884814/crash-2022-01-14_19.03.40-server.txt)
[crash-2022-01-15_02.43.13-server.txt](https://github.com/LunaPixelStudios/Better-Minecraft/files/7884815/crash-2022-01-15_02.43.13-server.txt)
[crash-2022-01-15_17.53.44-server.txt](https://github.com/LunaPixelStudios/Better-Minecraft/files/7884816/crash-2022-01-15_17.53.44-server.txt)
[crash-2022-01-14_00.05.44-server.txt](https://github.com/LunaPixelStudios/Better-Minecraft/files/7884817/crash-2022-01-14_00.05.44-server.txt)
[crash-2022-01-14_01.18.01-server.txt](https://github.com/LunaPixelStudios/Better-Minecraft/files/7884818/crash-2022-01-14_01.18.01-server.txt)
[crash-2022-01-15_21.43.08-server.txt](https://github.com/LunaPixelStudios/Better-Minecraft/files/7884819/crash-2022-01-15_21.43.08-server.txt)
[crash-2022-01-16_18.26.04-server.txt](https://github.com/LunaPixelStudios/Better-Minecraft/files/7884820/crash-2022-01-16_18.26.04-server.txt)
[crash-2022-01-16_20.30.39-server.txt](https://github.com/LunaPixelStudios/Better-Minecraft/files/7884821/crash-2022-01-16_20.30.39-server.txt)
[crash-2022-01-16_22.26.11-server.txt](https://github.com/LunaPixelStudios/Better-Minecraft/files/7884822/crash-2022-01-16_22.26.11-server.txt)
[crash-2022-01-16_22.57.48-server.txt](https://github.com/LunaPixelStudios/Better-Minecraft/files/7884823/crash-2022-01-16_22.57.48-server.txt)
[crash-2022-01-17_14.48.02-server.txt](https://github.com/LunaPixelStudios/Better-Minecraft/files/7884824/crash-2022-01-17_14.48.02-server.txt)
[crash-2022-01-17_15.03.04-server.txt](https://github.com/LunaPixelStudios/Better-Minecraft/files/7884825/crash-2022-01-17_15.03.04-server.txt)
[crash-2022-01-14_02.32.01-server.txt](https://github.com/LunaPixelStudios/Better-Minecraft/files/7884826/crash-2022-01-14_02.32.01-server.txt)

**Comment by kentros38** [comment]
I seemed to resolve a good portion of the lag by disabling the Blue Skies mod on path client and server side so that's great. Still could be better but it keeps saying
 "[Server] Server thread/WARN Found reference to unknown structure 'blue_skies:nature_dungeon' in chunk [-55, 182], discarding" 

but no overload messages so thats a start. 

 @GlitchDoctor01 tagged you to reference :)

**Comment by SharkieTV** [comment]
@kentros38 His is a different issue and not the same mods, yours using v12 which doesn't have the blue skies fix issue that's in v12.5. Either update to v12.5 or wait till I v13 comes out today.

**Comment by SharkieTV** [comment]
@kentros38 No you shouldn't loose anything and yes you might need to change the slots buts then what's the point of upgrading your backpack if you base will just be that big you know.

**Comment by kentros38** [comment]
the backpack thing was just annoying and we wanted it big soooo. Either way, just let me know when i can update our stuff and I will do that and report back. Friends want the blue skies mod so id love to get all this resolved for them :)

**Comment by SharkieTV** [comment]
Well 2 new updates for the packs came out for fabric and forge so hopefully it should fix the issues, if it doesnt for you @kentros38 then I might know whats causing it

**Comment by kentros38** [comment]
Hey saw you closed this, wanted to say it has 100 percent been running better. However, we have had a bit of an issue still with people using waystones or changing dimensions still. So if you know of anything that would maybe help with that then we can give it a shot but v13 has definitely helped us out. So thank you for everything so far
