### ISSUE TITLE
Modpack crashing every time i load in to the world

### ISSUE THREAD

**Issue by CalualaMic** [LunaPixelStudios/Better-Minecraft#64]
Like how the title says i can't open my world. Everytime I try it just crashes. This happened inthe forge version (v14) of the better minecraft 1.18.1. Here's the log if it can help (also this happened after i placed my simple storage blocks on the ground, and this happend every time i place a block)
[crash-2022-01-27_16.50.01-server.txt](https://github.com/LunaPixelStudios/Better-Minecraft/files/7951339/crash-2022-01-27_16.50.01-server.txt)
.

**Comment by switchnlade** [comment]
Remove Simple Storage Network

**Comment by CalualaMic** [comment]
> Remove Simple Storage Network from the mods folder

Alright but this happens with every block I place not only the Simple Storage Network blocks.

**Comment by switchnlade** [comment]
Slightly confused on here, were these crashes separate? If so, please give me one from when you placed a block that wasn't from SSN.

**Comment by CalualaMic** [comment]
But i see everytime i read the crash it says crash report-server. Does it have something to do that i opened my world to LAN, and thats why it always crashes?

**Comment by switchnlade** [comment]
You said you are on v14, and yet you are using jade v4.1.1 which is not the one in v14. That crash has been fixed in jade v4.1.2 which is included in v14 of our pack.

**Comment by CalualaMic** [comment]
Yes i know ,tho it still crashed then and it crashes even if I put the new version of Jade in the modpack again. The only version of the modpack i can play my world on its v12.5.

**Comment by switchnlade** [comment]
So what version are you actually on?

**Comment by CalualaMic** [comment]
Like on v14 i can only open my world and explore it without placing or destroyng any block.

**Comment by switchnlade** [comment]
Which block did you place to get the Jade crash? I can't get it despite looking at a furnace which is what caused that using v14.

**Comment by CalualaMic** [comment]
I did not place any block it just crashed every time i looked at something. Also i observed in a creative world that only when i place the root of the SSN it crashes. One more thing: i changed, a long time ago, my world spawn so when i place the SSN formation to stay loaded every time.

**Comment by switchnlade** [comment]
Alrighty, well to stop any more confusion, let's set this basis, have you tried to load the world without SSN? If so, please upload the latest.log (not the crash log, this one is in the logs folder). If you haven't please do so and if it crashes then, upload the latest.log.

**Comment by CalualaMic** [comment]
[latest.log](https://github.com/LunaPixelStudios/Better-Minecraft/files/7951792/latest.log)
Alright bro here you go. Tell me if you can help me.

**Comment by CalualaMic** [comment]
Also i saw that I can place any minecraft blocks (the unmodded ones) and it doesnt crash. Unfortunately i didnt use that many mods to see if they crash the world but i used immersive engineering which did not crash the world. Maybe its only the SSN

**Comment by CalualaMic** [comment]
Yeah i think the world is corrupted cuz i started playing since the v1 version of it and since then there where a lot of changes wich could corrupt my world. Like when the fruit trees mod got removed the forest next to my house looked like Herobrine was there i swear. Well thanks for the help. Hope you fix the SSN crash thingy. See ya .
